[__config__]
oldver = "oldver.json"
newver = "newver.json"

[gams]
source = "pypi"
pypi = "gamspy-base"

[niri-companion]
source = "github"
github = "dybdeskarphet/niri-companion"
use_latest_release = true
prefix = "v"

[ungoogled-chromium-widevine-bin]
source = "github"
github = "ungoogled-software/ungoogled-chromium-archlinux"
use_latest_release = true
from_pattern = '^(\d+\.\d+\.\d+\.\d+)-\d+$'
to_pattern = '\1'

[deskreen-ce-bin]
source = "github"
github = "pavlobu/deskreen"
use_latest_release = true
prefix = "v"

[gtkcsslanguageserver-git]
source = "github"
github = "JCWasmx86/GTKCssLanguageServer"
use_latest_commit = true

[antigravity-cli]
source = "jq"
url = "https://antigravity-cli-auto-updater-974169037036.us-central1.run.app/manifests/linux_amd64.json"
filter = ".url | split(\"/\")[5]"
from_pattern = "-"
to_pattern = "_"
